### ISSUE TITLE
Getting This Issue

### ISSUE THREAD

**Issue by Anonymous327** [Aeroblast/UnpackKindleS#14]
Getting this issue. 怎麽辦？
![image](https://user-images.githubusercontent.com/96669859/147395969-7428ad98-1cb0-4f80-8685-4bc3600b5190.png)

**Comment by Aeroblast** [comment]
Your book is in KFX format, and my tool is for KF8 + HD Container. Follow [this page](https://github.com/noDRM/DeDRM_tools/blob/master/FAQs.md#recent-changes-to-kindle-for-pckindle-for-mac).

In short, delete 'renderer-test.exe' and the Kindle client will give you KF8 format. 
I've never tried that because I use amazon jp and they always serve KF8, but it's worth a try. Good luck.
